-- MySQL Script generated by MySQL Workbench
-- jue 27 oct 2016 17:34:00 CLST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema verdor_database
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `verdor_database` ;

-- -----------------------------------------------------
-- Schema verdor_database
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `verdor_database` DEFAULT CHARACTER SET utf8 ;
USE `verdor_database` ;

-- -----------------------------------------------------
-- Table `verdor_database`.`figuras_geograficas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `verdor_database`.`figuras_geograficas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `figura` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `verdor_database`.`parcelas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `verdor_database`.`parcelas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `superficie` DECIMAL(10,2) NOT NULL,
  `direccion` VARCHAR(256) NOT NULL,
  `latitud` DECIMAL(10,8) NULL DEFAULT 0,
  `longitud` DECIMAL(11,8) NULL DEFAULT 0,
  `nombre` VARCHAR(256) NOT NULL,
  `figuras_geograficas_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_parcelas_figuras_geograficas1_idx` (`figuras_geograficas_id` ASC),
  CONSTRAINT `fk_parcelas_figuras_geograficas1`
    FOREIGN KEY (`figuras_geograficas_id`)
    REFERENCES `verdor_database`.`figuras_geograficas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `verdor_database`.`sectores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `verdor_database`.`sectores` (
  `id` INT NOT NULL,
  `parcelas_id` INT NOT NULL,
  `tipos_sectores_id` INT NOT NULL,
  `figuras_geograficas_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sectores_parcelas1_idx` (`parcelas_id` ASC),
  INDEX `fk_sectores_figuras_geograficas1_idx` (`figuras_geograficas_id` ASC),
  CONSTRAINT `fk_sectores_parcelas1`
    FOREIGN KEY (`parcelas_id`)
    REFERENCES `verdor_database`.`parcelas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sectores_figuras_geograficas1`
    FOREIGN KEY (`figuras_geograficas_id`)
    REFERENCES `verdor_database`.`figuras_geograficas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `verdor_database`.`plantas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `verdor_database`.`plantas` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre_comun` VARCHAR(256) NOT NULL,
  `nombre_cientifico` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `verdor_database`.`cultivos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `verdor_database`.`cultivos` (
  `id` INT(11) NOT NULL,
  `fecha_siembra` DATE NULL DEFAULT NULL,
  `fecha_cosecha` DATE NULL DEFAULT NULL,
  `sectores_id` INT NOT NULL,
  `plantas_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cultivos_sectores1_idx` (`sectores_id` ASC),
  INDEX `fk_cultivos_plantas1_idx` (`plantas_id` ASC),
  CONSTRAINT `fk_cultivos_sectores1`
    FOREIGN KEY (`sectores_id`)
    REFERENCES `verdor_database`.`sectores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cultivos_plantas1`
    FOREIGN KEY (`plantas_id`)
    REFERENCES `verdor_database`.`plantas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `verdor_database`.`controladores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `verdor_database`.`controladores` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `serie` VARCHAR(45) NULL,
  `estado` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `verdor_database`.`actuadores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `verdor_database`.`actuadores` (
  `id` VARCHAR(45) NOT NULL,
  `modelo` VARCHAR(45) NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `verdor_database`.`controladores_actuadores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `verdor_database`.`controladores_actuadores` (
  `controladores_id` INT(11) NOT NULL,
  `actuadores_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`controladores_id`, `actuadores_id`),
  INDEX `fk_controladores_has_actuadores_actuadores1_idx` (`actuadores_id` ASC),
  INDEX `fk_controladores_has_actuadores_controladores1_idx` (`controladores_id` ASC),
  CONSTRAINT `fk_controladores_has_actuadores_controladores1`
    FOREIGN KEY (`controladores_id`)
    REFERENCES `verdor_database`.`controladores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_controladores_has_actuadores_actuadores1`
    FOREIGN KEY (`actuadores_id`)
    REFERENCES `verdor_database`.`actuadores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `verdor_database`.`instrucciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `verdor_database`.`instrucciones` (
  `id` INT(11) NOT NULL,
  `fecha_emision` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `controladores_actuadores_controladores_id` INT(11) NOT NULL,
  `controladores_actuadores_actuadores_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_instrucciones_controladores_actuadores1_idx` (`controladores_actuadores_controladores_id` ASC, `controladores_actuadores_actuadores_id` ASC),
  CONSTRAINT `fk_instrucciones_controladores_actuadores1`
    FOREIGN KEY (`controladores_actuadores_controladores_id` , `controladores_actuadores_actuadores_id`)
    REFERENCES `verdor_database`.`controladores_actuadores` (`controladores_id` , `actuadores_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `verdor_database`.`sensores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `verdor_database`.`sensores` (
  `rango_minimo` VARCHAR(45) NULL,
  `rango_maximo` VARCHAR(45) NULL,
  `id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `verdor_database`.`controladores_sensores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `verdor_database`.`controladores_sensores` (
  `controladores_id` INT(11) NOT NULL,
  `sensores_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`controladores_id`, `sensores_id`),
  INDEX `fk_controladores_has_sensores_sensores1_idx` (`sensores_id` ASC),
  INDEX `fk_controladores_has_sensores_controladores1_idx` (`controladores_id` ASC),
  CONSTRAINT `fk_controladores_has_sensores_controladores1`
    FOREIGN KEY (`controladores_id`)
    REFERENCES `verdor_database`.`controladores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_controladores_has_sensores_sensores1`
    FOREIGN KEY (`sensores_id`)
    REFERENCES `verdor_database`.`sensores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `verdor_database`.`mediciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `verdor_database`.`mediciones` (
  `id_medicion` INT(11) NOT NULL AUTO_INCREMENT,
  `valor` DECIMAL(10,4) NOT NULL,
  `fecha` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `controladores_sensores_controladores_id` INT(11) NOT NULL,
  `controladores_sensores_sensores_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_medicion`),
  INDEX `fk_mediciones_controladores_sensores1_idx` (`controladores_sensores_controladores_id` ASC, `controladores_sensores_sensores_id` ASC),
  CONSTRAINT `fk_mediciones_controladores_sensores1`
    FOREIGN KEY (`controladores_sensores_controladores_id` , `controladores_sensores_sensores_id`)
    REFERENCES `verdor_database`.`controladores_sensores` (`controladores_id` , `sensores_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `verdor_database`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `verdor_database`.`roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(256) NOT NULL,
  `descripcion` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `verdor_database`.`servicios_parcelas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `verdor_database`.`servicios_parcelas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha_inicio` DATE NOT NULL,
  `fecha_termino` DATE NOT NULL,
  `precio` DECIMAL(12,2) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `verdor_database`.`servicios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `verdor_database`.`servicios` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(256) NOT NULL,
  `precio` DECIMAL(12,2) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `verdor_database`.`ordenes_muestreos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `verdor_database`.`ordenes_muestreos` (
  `id` INT NOT NULL,
  `fecha_orden` VARCHAR(45) NULL,
  `motivo` VARCHAR(45) NULL,
  `comentarios` VARCHAR(45) NULL,
  `parcelas_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ordenes_muestreos_parcelas1_idx` (`parcelas_id` ASC),
  CONSTRAINT `fk_ordenes_muestreos_parcelas1`
    FOREIGN KEY (`parcelas_id`)
    REFERENCES `verdor_database`.`parcelas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `verdor_database`.`muestras_suelo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `verdor_database`.`muestras_suelo` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `metodo_muestreo` VARCHAR(45) NULL,
  `color` VARCHAR(45) NULL,
  `textura` VARCHAR(45) NULL,
  `estructura` VARCHAR(45) NULL,
  `fecha_muestra` VARCHAR(45) NULL,
  `latitud` VARCHAR(45) NULL,
  `longitud` VARCHAR(45) NULL,
  `instrumento` VARCHAR(45) NULL,
  `profundidad` VARCHAR(45) NULL,
  `submuestras` VARCHAR(45) NULL,
  `hectareas_representa` VARCHAR(45) NULL,
  `ordenes_muestreos_id` INT NOT NULL,
  INDEX `fk_muestra_suelos_ordenes_muestreos1_idx` (`ordenes_muestreos_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_muestra_suelos_ordenes_muestreos1`
    FOREIGN KEY (`ordenes_muestreos_id`)
    REFERENCES `verdor_database`.`ordenes_muestreos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `verdor_database`.`variables`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `verdor_database`.`variables` (
  `id` INT(11) NOT NULL,
  `nombre` VARCHAR(256) NOT NULL,
  `descripcion` VARCHAR(256) NULL DEFAULT NULL,
  `sigla` VARCHAR(10) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `unidad_medida` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `verdor_database`.`personas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `verdor_database`.`personas` (
  `dni` VARCHAR(20) NOT NULL,
  `nombres` VARCHAR(256) NOT NULL,
  `apellido_pat` VARCHAR(256) NULL DEFAULT NULL,
  `apelllido_mat` VARCHAR(256) NULL DEFAULT NULL,
  `fecha_nac` DATE NULL DEFAULT NULL,
  `direccion` VARCHAR(256) NULL DEFAULT NULL,
  `telefono` VARCHAR(20) NULL DEFAULT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `dni_UNIQUE` (`dni` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `verdor_database`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `verdor_database`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(100) NOT NULL,
  `nombreusuario` VARCHAR(100) NOT NULL,
  `contrasena` VARCHAR(100) NOT NULL,
  `personas_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usuarios_personas1_idx` (`personas_id` ASC),
  CONSTRAINT `fk_usuarios_personas1`
    FOREIGN KEY (`personas_id`)
    REFERENCES `verdor_database`.`personas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `verdor_database`.`usuarios_parcelas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `verdor_database`.`usuarios_parcelas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuarios_id` INT NOT NULL,
  `parcelas_id` INT(11) NOT NULL,
  `roles_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usuario_parcela_usuarios1_idx` (`usuarios_id` ASC),
  INDEX `fk_usuario_parcela_parcelas1_idx` (`parcelas_id` ASC),
  INDEX `fk_usuario_parcela_roles1_idx` (`roles_id` ASC),
  CONSTRAINT `fk_usuario_parcela_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `verdor_database`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_parcela_parcelas1`
    FOREIGN KEY (`parcelas_id`)
    REFERENCES `verdor_database`.`parcelas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_parcela_roles1`
    FOREIGN KEY (`roles_id`)
    REFERENCES `verdor_database`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `verdor_database`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `verdor_database`.`clientes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `verdor_database`.`analisis_suelo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `verdor_database`.`analisis_suelo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `muestras_suelo_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_analisis_suelo_muestras_suelo1_idx` (`muestras_suelo_id` ASC),
  CONSTRAINT `fk_analisis_suelo_muestras_suelo1`
    FOREIGN KEY (`muestras_suelo_id`)
    REFERENCES `verdor_database`.`muestras_suelo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `verdor_database`.`examenes_visuales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `verdor_database`.`examenes_visuales` (
  `id` INT NOT NULL,
  `ordenes_muestreos_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_examen_visual_ordenes_muestreos1_idx` (`ordenes_muestreos_id` ASC),
  CONSTRAINT `fk_examen_visual_ordenes_muestreos1`
    FOREIGN KEY (`ordenes_muestreos_id`)
    REFERENCES `verdor_database`.`ordenes_muestreos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `verdor_database`.`muestras_agua`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `verdor_database`.`muestras_agua` (
  `id` INT NOT NULL,
  `ordenes_muestreos_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_muestras_agua_ordenes_muestreos1_idx` (`ordenes_muestreos_id` ASC),
  CONSTRAINT `fk_muestras_agua_ordenes_muestreos1`
    FOREIGN KEY (`ordenes_muestreos_id`)
    REFERENCES `verdor_database`.`ordenes_muestreos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `verdor_database`.`muestras_biologicas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `verdor_database`.`muestras_biologicas` (
  `id` INT NOT NULL,
  `ordenes_muestreos_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_muestras_biologicas_ordenes_muestreos1_idx` (`ordenes_muestreos_id` ASC),
  CONSTRAINT `fk_muestras_biologicas_ordenes_muestreos1`
    FOREIGN KEY (`ordenes_muestreos_id`)
    REFERENCES `verdor_database`.`ordenes_muestreos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `verdor_database`.`sectores_controladores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `verdor_database`.`sectores_controladores` (
  `sectores_id` INT NOT NULL,
  `controladores_id` INT(11) NOT NULL,
  `fecha_instalacion` DATE NULL,
  `fecha_baja` DATE NULL,
  INDEX `fk_sectores_has_controladores_controladores1_idx` (`controladores_id` ASC),
  PRIMARY KEY (`sectores_id`, `controladores_id`),
  CONSTRAINT `fk_sectores_has_controladores_sectores1`
    FOREIGN KEY (`sectores_id` , `controladores_id`)
    REFERENCES `verdor_database`.`sectores` (`id` , `id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sectores_has_controladores_controladores1`
    FOREIGN KEY (`controladores_id`)
    REFERENCES `verdor_database`.`controladores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `verdor_database`.`categorias_taxonomicas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `verdor_database`.`categorias_taxonomicas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `categoria_padre_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_categorias_taxonomicas_categorias_taxonomicas1_idx` (`categoria_padre_id` ASC),
  CONSTRAINT `fk_categorias_taxonomicas_categorias_taxonomicas1`
    FOREIGN KEY (`categoria_padre_id`)
    REFERENCES `verdor_database`.`categorias_taxonomicas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `verdor_database`.`taxonomias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `verdor_database`.`taxonomias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `plantas_id` INT(11) NOT NULL,
  `categorias_taxonomicas_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_taxonomia_plantas1_idx` (`plantas_id` ASC),
  INDEX `fk_taxonomia_categorias_taxonomicas1_idx` (`categorias_taxonomicas_id` ASC),
  CONSTRAINT `fk_taxonomia_plantas1`
    FOREIGN KEY (`plantas_id`)
    REFERENCES `verdor_database`.`plantas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_taxonomia_categorias_taxonomicas1`
    FOREIGN KEY (`categorias_taxonomicas_id`)
    REFERENCES `verdor_database`.`categorias_taxonomicas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `verdor_database`.`valores_limites`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `verdor_database`.`valores_limites` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `plantas_id` INT(11) NOT NULL,
  `variables_id` INT(11) NOT NULL,
  `minimo` VARCHAR(45) NULL,
  `maximo` VARCHAR(45) NULL,
  PRIMARY KEY (`plantas_id`, `variables_id`),
  INDEX `fk_valores_limites_plantas1_idx` (`plantas_id` ASC),
  INDEX `fk_valores_limites_variables1_idx` (`variables_id` ASC),
  CONSTRAINT `fk_valores_limites_plantas1`
    FOREIGN KEY (`plantas_id`)
    REFERENCES `verdor_database`.`plantas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_valores_limites_variables1`
    FOREIGN KEY (`variables_id`)
    REFERENCES `verdor_database`.`variables` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `verdor_database`.`sensores_variables`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `verdor_database`.`sensores_variables` (
  `sensores_id` VARCHAR(45) NOT NULL,
  `variables_id` INT(11) NOT NULL,
  PRIMARY KEY (`sensores_id`, `variables_id`),
  INDEX `fk_sensores_has_variables_variables1_idx` (`variables_id` ASC),
  INDEX `fk_sensores_has_variables_sensores1_idx` (`sensores_id` ASC),
  CONSTRAINT `fk_sensores_has_variables_sensores1`
    FOREIGN KEY (`sensores_id`)
    REFERENCES `verdor_database`.`sensores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sensores_has_variables_variables1`
    FOREIGN KEY (`variables_id`)
    REFERENCES `verdor_database`.`variables` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `verdor_database`.`actuadores_variables`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `verdor_database`.`actuadores_variables` (
  `actuadores_id` VARCHAR(45) NOT NULL,
  `variables_id` INT(11) NOT NULL,
  PRIMARY KEY (`actuadores_id`, `variables_id`),
  INDEX `fk_actuadores_has_variables_variables1_idx` (`variables_id` ASC),
  INDEX `fk_actuadores_has_variables_actuadores1_idx` (`actuadores_id` ASC),
  CONSTRAINT `fk_actuadores_has_variables_actuadores1`
    FOREIGN KEY (`actuadores_id`)
    REFERENCES `verdor_database`.`actuadores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_actuadores_has_variables_variables1`
    FOREIGN KEY (`variables_id`)
    REFERENCES `verdor_database`.`variables` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
